// FILE: project-document-body.ts
// PURPOSE: Deterministic structured body for project-linked Google Docs.
//          Distinguishes confirmed / proposed / unresolved. Never invents
//          facts not supplied by the caller. Used by project-document.service
//          before provider create so empty shells cannot pass acceptance.
// CONNECTS TO: google-doc.service.ts, work-project.service.ts

export type FactStatus = "confirmed" | "proposed" | "rejected" | "unresolved" | "corrected";

export interface StructuredFact {
  text: string;
  status: FactStatus;
  owner_label?: string;
}

export interface ProjectDocumentSections {
  objective?: string;
  scope?: StructuredFact[];
  decisions?: StructuredFact[];
  requirements?: StructuredFact[];
  owners?: Array<{ role: string; name: string }>;
  timeline?: StructuredFact[];
  meeting?: StructuredFact[];
  dependencies?: StructuredFact[];
  risks?: StructuredFact[];
  compliance?: StructuredFact[];
  open_questions?: StructuredFact[];
  next_actions?: StructuredFact[];
  source_note?: string;
}

export interface BuildProjectDocumentBodyInput {
  project_name: string;
  organization_label?: string;
  artifact_type?: string;
  sections: ProjectDocumentSections;
  generated_at_iso?: string;
}

const MIN_USEFUL_BODY_CHARS = 280;

export function minUsefulBodyChars(): number {
  return MIN_USEFUL_BODY_CHARS;
}

function lineFact(f: StructuredFact): string {
  const tag = f.status.toUpperCase();
  const owner =
    typeof f.owner_label === "string" && f.owner_label.trim().length > 0
      ? ` · owner: ${f.owner_label.trim()}`
      : "";
  return `- [${tag}] ${f.text.trim()}${owner}`;
}

function section(title: string, lines: string[]): string[] {
  if (lines.length === 0) return [];
  return [`## ${title}`, ...lines, ""];
}

// WHAT: Build a non-empty structured project document body from supplied facts.
// WHY: Provider create must carry organizational content, not a shell.
//      Missing sections are omitted (not fabricated).
export function buildProjectDocumentBody(
  input: BuildProjectDocumentBodyInput,
): { body: string; char_count: number; section_count: number } {
  const when = input.generated_at_iso ?? new Date().toISOString();
  const artifact = input.artifact_type ?? "Project brief";
  const org =
    typeof input.organization_label === "string" &&
    input.organization_label.trim().length > 0
      ? input.organization_label.trim()
      : "Organization";

  const s = input.sections;
  const parts: string[] = [
    `# ${artifact}: ${input.project_name.trim()}`,
    "",
    `_Generated by Otzar from project context · ${when}_`,
    `_Org: ${org}_`,
    "",
    "Status legend: CONFIRMED · PROPOSED · REJECTED · UNRESOLVED · CORRECTED",
    "",
  ];

  if (typeof s.objective === "string" && s.objective.trim().length > 0) {
    parts.push(...section("1. Objective", [s.objective.trim()]));
  }
  if (s.scope?.length) {
    parts.push(...section("2. Current approved scope", s.scope.map(lineFact)));
  }
  if (s.decisions?.length) {
    parts.push(...section("3. Key decisions", s.decisions.map(lineFact)));
  }
  if (s.requirements?.length) {
    parts.push(...section("4. Requirements", s.requirements.map(lineFact)));
  }
  if (s.owners?.length) {
    parts.push(
      ...section(
        "5. Owners",
        s.owners.map((o) => `- ${o.role.trim()}: ${o.name.trim()}`),
      ),
    );
  }
  if (s.timeline?.length) {
    parts.push(...section("6. Timeline", s.timeline.map(lineFact)));
  }
  if (s.meeting?.length) {
    parts.push(...section("7. Meeting", s.meeting.map(lineFact)));
  }
  if (s.dependencies?.length) {
    parts.push(...section("8. Dependencies", s.dependencies.map(lineFact)));
  }
  if (s.risks?.length) {
    parts.push(...section("9. Risks", s.risks.map(lineFact)));
  }
  if (s.compliance?.length) {
    parts.push(...section("10. Compliance restrictions", s.compliance.map(lineFact)));
  }
  if (s.open_questions?.length) {
    parts.push(...section("11. Open questions", s.open_questions.map(lineFact)));
  }
  if (s.next_actions?.length) {
    parts.push(...section("12. Next actions", s.next_actions.map(lineFact)));
  }
  const source =
    typeof s.source_note === "string" && s.source_note.trim().length > 0
      ? s.source_note.trim()
      : "Derived only from supplied project facts. Unstated items are omitted, not invented.";
  parts.push(...section("13. Source and revision note", [source]));

  const body = parts.join("\n").trim() + "\n";
  const section_count = (body.match(/^## /gm) ?? []).length;
  return { body, char_count: body.length, section_count };
}

// WHAT: Acceptance gate for a useful document body.
// WHY: Empty / near-empty provider shells must fail functional proof.
export function isUsefulDocumentBody(body: string): boolean {
  const t = body.trim();
  if (t.length < MIN_USEFUL_BODY_CHARS) return false;
  // At least one structured section heading.
  if (!/^##\s+\d+\./m.test(t) && !/^##\s+/m.test(t)) return false;
  return true;
}
