defmodule CosmpRouter.Audit do
  @moduledoc """
  Audit primitive for the COSMP coordination layer per ADR-0033
  §Decision 4. Byte-equivalent port of the Foundation TypeScript
  register at `packages/database/src/queries/audit.ts` so
  `verify_audit_chain` running in either language register produces
  identical hash sequences for identical canonical inputs.

  ## Core primitives

  - `canonical_json/1` — recursive sorted-key JSON-like serialization
    matching `audit.ts:252-268` byte-for-byte
  - `canonical_record/1` — 12-field pipe-joined record string matching
    `audit.ts:276-303` byte-for-byte
  - `sha256_hex/1` — `:crypto.hash(:sha256, input) |> Base.encode16(case: :lower)`
    matching `crypto.ts:94-96` `createHash("sha256").update(input).digest("hex")`
  - `chain_key/1` — `actor_entity_id ?? system_principal ?? @system_chain_key`
    priority resolution matching `audit.ts:370-371` (per ADR-0006)

  ## Cross-language byte-equivalence discipline

  The byte-equivalence invariant is verified by
  `apps/cosmp_router/test/cosmp_router/audit/canonical_record_test.exs`
  using fixtures generated by
  `scripts/generate-canonical-fixtures.ts`. ANY changes to
  serialization discipline at either register MUST regenerate
  fixtures + verify Elixir port matches.

  **`DateTime.truncate(:millisecond)` is load-bearing** per ADR-0033
  §Decision 4a — TypeScript `Date.toISOString()` always emits
  millisecond precision; Elixir `DateTime.to_iso8601/1` defaults to
  microsecond. Truncation preserves byte-equivalence at the timestamp
  field.

  ## Dual-mode `write_audit_event`

  Mirrors TS `writeAuditEvent` at `audit.ts:452-460`:

  - `write_audit_event/1` — standalone mode; opens own Repo transaction
  - `write_audit_event/3` — composed mode; participates in caller's
    `Ecto.Multi`

  RULE 4 + ADR-0026 §5 Pattern 4 compound: COSMP `WRITE` / `SHARE` /
  `REVOKE` ops use composed mode (audit failure rolls back business
  mutation atomically). `READ` / `AUDIT` lookup ops use standalone
  (no business mutation to roll back).

  ## SYSTEM_PRINCIPALS

  Mirrors `audit.ts:235-240` SYSTEM_PRINCIPALS frozen registry +
  ADR-0033 §Decision 4d 5th principal `:cosmp_router` for Elixir
  register subsystem attribution.

  ## References

  - ADR-0033 §Decision 4 (audit primitive byte-equivalence)
  - ADR-0002 (Append-only audit chain; SHA-256 hash chain canonical)
  - ADR-0006 (chainKey priority)
  - ADR-0026 §5 Pattern 4 (event-sourced audit)
  - `packages/database/src/queries/audit.ts` (TS register source-of-truth)
  - `packages/auth/src/crypto.ts:94-96` (sha256Hex TS reference)
  """

  @system_chain_key "__niov_system_chain__"

  @system_principals %{
    scheduler: "__niov_system_scheduler__",
    boot_validator: "__niov_system_boot_validator__",
    compliance_seeder: "__niov_system_compliance_seeder__",
    feedback_loop: "__niov_system_feedback_loop__",
    cosmp_router: "__niov_system_cosmp_router__"
  }

  @doc """
  Returns the SYSTEM_PRINCIPALS map. Equivalent to TypeScript's
  `SYSTEM_PRINCIPALS` frozen object at `audit.ts:235-240`. Includes
  the `:cosmp_router` 5th principal added at sub-phase 5b-ii per
  ADR-0033 §Decision 4d.
  """
  def system_principals, do: @system_principals

  @doc """
  Returns the legacy SYSTEM_CHAIN_KEY sentinel for backwards-compat
  fallback per DRIFT 12 anchor at `audit.ts:219`.
  """
  def system_chain_key, do: @system_chain_key

  @doc """
  Resolve the chain_key for an audit event input per ADR-0006 priority:
  `actor_entity_id || system_principal || @system_chain_key`.

  Mirrors TypeScript `audit.ts:370-371`.
  """
  def chain_key(input) when is_map(input) do
    cond do
      truthy?(input[:actor_entity_id]) -> input[:actor_entity_id]
      truthy?(input[:system_principal]) -> input[:system_principal]
      true -> @system_chain_key
    end
  end

  defp truthy?(nil), do: false
  defp truthy?(""), do: false
  defp truthy?(_), do: true

  @doc """
  SHA-256 hex digest of the canonical record string.

  Mirrors TypeScript `crypto.ts:94-96` + `audit.ts:310-312`:
    `createHash("sha256").update(input).digest("hex")`
  Elixir equivalent:
    `:crypto.hash(:sha256, input) |> Base.encode16(case: :lower)`

  Returns a 64-character lowercase hex string.
  """
  def sha256_hex(input) when is_binary(input) do
    :crypto.hash(:sha256, input) |> Base.encode16(case: :lower)
  end

  @doc """
  Canonical 14-field pipe-joined record string for hashing per ADR-0033
  §Decision 4a (extended at sub-phase 4 [SUB-BOX-3-AUDIT-CHAIN-EXTENSION]
  per ADR-0036 Sub-decision 5 hybrid binding from 12 → 14 fields).
  Mirrors TypeScript `audit.ts:276-303` `canonicalRecord` byte-for-byte.

  ## Field order (load-bearing; do NOT reorder)

  1. audit_id
  2. event_type
  3. actor_entity_id (or "" if nil)
  4. target_entity_id (or "" if nil)
  5. target_capsule_id (or "" if nil)
  6. session_id (or "" if nil)
  7. outcome
  8. denial_reason (or "" if nil)
  9. canonical_json(details)
  10. ip_address (or "" if nil)
  11. timestamp truncated to millisecond + ISO 8601
  12. previous_event_hash (or "" if nil)
  13. lawful_basis_id (or "" if nil) — ADR-0036 Sub-decision 5
  14. lawful_basis_chain_hash (or "" if nil) — ADR-0036 Sub-decision 5

  Joined with "|" delimiter. ANY field-order or delimiter change breaks
  cross-language hash equivalence.
  """
  def canonical_record(parts) when is_map(parts) do
    [
      parts.audit_id,
      parts.event_type,
      parts[:actor_entity_id] || "",
      parts[:target_entity_id] || "",
      parts[:target_capsule_id] || "",
      parts[:session_id] || "",
      parts.outcome,
      parts[:denial_reason] || "",
      canonical_json(parts.details),
      parts[:ip_address] || "",
      iso8601_millisecond(parts.timestamp),
      parts[:previous_event_hash] || "",
      parts[:lawful_basis_id] || "",
      parts[:lawful_basis_chain_hash] || ""
    ]
    |> Enum.join("|")
  end

  @doc """
  Recursive sorted-key JSON-like canonical serialization per ADR-0033
  §Decision 4b. Mirrors TypeScript `audit.ts:252-268` `canonicalJson`
  byte-for-byte.

  ## Discipline

  - Primitives (string, number, boolean, nil) → `Jason.encode!/1`
    (matches `JSON.stringify` byte output for all standard JSON values)
  - Arrays → `"[" + comma-joined recursive + "]"` (no whitespace;
    elements preserve insertion order)
  - Maps → keys converted to strings + sorted alphabetically + emitted
    as `"{" + comma-joined "key:value" + "}"` (no whitespace)
  - Recursive on map values + array elements

  Maps with mixed atom/string keys are normalized to string keys
  before sorting — Elixir convention is atom keys but JSON canonical
  form is string keys.
  """
  def canonical_json(nil), do: "null"

  def canonical_json(value)
      when is_boolean(value) or is_number(value) or is_binary(value) do
    Jason.encode!(value)
  end

  def canonical_json(value) when is_list(value) do
    inner = value |> Enum.map(&canonical_json/1) |> Enum.join(",")
    "[" <> inner <> "]"
  end

  def canonical_json(value) when is_map(value) do
    pairs =
      value
      |> Enum.map(fn {k, v} -> {to_string(k), v} end)
      |> Enum.sort_by(fn {k, _} -> k end)

    inner =
      pairs
      |> Enum.map(fn {k, v} ->
        Jason.encode!(k) <> ":" <> canonical_json(v)
      end)
      |> Enum.join(",")

    "{" <> inner <> "}"
  end

  # Truncate to millisecond precision before ISO 8601 emission so
  # output matches TypeScript Date.toISOString() byte-for-byte
  # (TS always emits millisecond precision; Elixir defaults to
  # microsecond).
  defp iso8601_millisecond(%DateTime{} = dt) do
    dt |> DateTime.truncate(:millisecond) |> DateTime.to_iso8601()
  end

  defp iso8601_millisecond(iso_string) when is_binary(iso_string) do
    # Allow callers to pre-format; assume already millisecond-precision
    # ISO 8601 string from TS-compatible source.
    iso_string
  end

  # ============================================================================
  # write_audit_event dual-mode (standalone + composed via Ecto.Multi)
  # per ADR-0033 §Decision 4e
  # ============================================================================

  alias CosmpRouter.{Repo, AuditEvent}
  import Ecto.Query, only: [from: 2]

  @doc """
  Standalone-mode audit-event write per ADR-0033 §Decision 4e + RULE 4.
  Opens its own Repo transaction; the audit row commits atomically with
  itself.

  Use from event-sourced patterns where each emission is independently
  meaningful (READ + AUDIT lookup ops in COSMP). For business-mutation
  ops (WRITE + SHARE + REVOKE), use `write_audit_event/3` composed
  mode so audit failure rolls back the business mutation atomically.

  Mirrors TypeScript `writeAuditEvent(input)` at `audit.ts:452-460`.

  ## Returns

  `{:ok, %CosmpRouter.AuditEvent{}}` on success or `{:error, changeset}`
  on validation/insert failure.
  """
  def write_audit_event(input) when is_map(input) do
    Repo.transaction(fn ->
      case write_audit_event_in_tx(input) do
        {:ok, event} -> event
        {:error, reason} -> Repo.rollback(reason)
      end
    end)
  end

  @doc """
  Composed-mode audit-event write per ADR-0033 §Decision 4e + RULE 4.
  Participates in the caller's `Ecto.Multi`; audit row commits or
  rolls back atomically with the caller's business mutation.

  COSMP `WRITE` / `SHARE` / `REVOKE` use composed mode per RULE 4 +
  ADR-0026 §5 Pattern 4 compound discipline.

  Mirrors TypeScript `writeAuditEvent(input, tx)` composed-mode at
  `audit.ts:452-460`.
  """
  def write_audit_event(input, %Ecto.Multi{} = multi, multi_key) when is_map(input) do
    Ecto.Multi.run(multi, multi_key, fn _repo, _changes ->
      write_audit_event_in_tx(input)
    end)
  end

  # WHAT: Inner transaction body — acquire per-chain advisory lock,
  #        look up previous_event_hash, compute event_hash, insert row.
  # INPUT: An audit event input map.
  # OUTPUT: {:ok, %AuditEvent{}} or {:error, reason}.
  # WHY: Mirrors TS audit.ts:359 writeAuditEventInTx exactly. The
  #      advisory lock is acquired in whichever transaction is live so
  #      per-chain serialization works in both standalone + composed
  #      modes.
  defp write_audit_event_in_tx(input) do
    chain_key_str = chain_key(input)

    # Per-chain advisory lock; xact-scoped (released on tx commit/rollback).
    # Mirrors TS audit.ts:374-377 pg_advisory_xact_lock(hashtext($chainKey)).
    Ecto.Adapters.SQL.query!(
      Repo,
      "SELECT pg_advisory_xact_lock(hashtext($1))",
      [chain_key_str]
    )

    # Previous event hash lookup scoped to actor_entity_id chain (matches
    # TS audit.ts:379-385 chain selection).
    previous_event_hash = previous_hash_for(input[:actor_entity_id])

    audit_id = Ecto.UUID.generate()
    # Microsecond-precision DateTime for Postgres storage; canonical_record
    # truncates to millisecond at hash time per ADR-0033 §Decision 4a.
    # Postgres stores full microsecond; canonical_record produces
    # byte-equivalent hash to TS Date.toISOString() (millisecond).
    timestamp = DateTime.utc_now()

    # 12C.0 Item 7: merge system_principal into details (matches
    # TS audit.ts:389-398).
    details =
      case input[:system_principal] do
        nil -> input[:details] || %{}
        sp -> Map.put(input[:details] || %{}, :system_principal, sp)
      end

    event_hash =
      sha256_hex(
        canonical_record(%{
          audit_id: audit_id,
          event_type: input.event_type,
          actor_entity_id: input[:actor_entity_id],
          target_entity_id: input[:target_entity_id],
          target_capsule_id: input[:target_capsule_id],
          session_id: input[:session_id],
          outcome: input.outcome,
          denial_reason: input[:denial_reason],
          details: details,
          ip_address: input[:ip_address],
          timestamp: timestamp,
          previous_event_hash: previous_event_hash,
          lawful_basis_id: input[:lawful_basis_id],
          lawful_basis_chain_hash: input[:lawful_basis_chain_hash]
        })
      )

    %AuditEvent{
      audit_id: audit_id,
      event_type: input.event_type,
      actor_entity_id: input[:actor_entity_id],
      target_entity_id: input[:target_entity_id],
      target_capsule_id: input[:target_capsule_id],
      session_id: input[:session_id],
      outcome: input.outcome,
      denial_reason: input[:denial_reason],
      details: details,
      ip_address: input[:ip_address],
      timestamp: timestamp,
      previous_event_hash: previous_event_hash,
      event_hash: event_hash,
      lawful_basis_id: input[:lawful_basis_id],
      lawful_basis_chain_hash: input[:lawful_basis_chain_hash]
    }
    |> Repo.insert()
  end

  defp previous_hash_for(nil) do
    from(a in AuditEvent,
      where: is_nil(a.actor_entity_id),
      order_by: [desc: a.timestamp],
      limit: 1,
      select: a.event_hash
    )
    |> Repo.one()
  end

  defp previous_hash_for(actor_entity_id) when is_binary(actor_entity_id) do
    from(a in AuditEvent,
      where: a.actor_entity_id == ^actor_entity_id,
      order_by: [desc: a.timestamp],
      limit: 1,
      select: a.event_hash
    )
    |> Repo.one()
  end

  # ============================================================================
  # verify_audit_chain — chain integrity check
  # per ADR-0033 §Decision 4f
  # ============================================================================

  @doc """
  Walk the audit-events chain for a given actor_entity_id (or nil for
  the system chain) ordered by timestamp; recompute every event_hash
  from canonical_record/1 + sha256_hex/1; assert each matches the
  stored hash AND each previous_event_hash matches the prior row's
  stored hash.

  Mirrors TypeScript `verifyAuditChain` at `audit.ts:514+`.

  ## Returns

  - `{:ok, count}` — chain verified; `count` events checked
  - `{:error, %{broken_at_audit_id: id, expected_hash: h1, computed_hash: h2}}`
    — first row where stored hash diverges from recomputed hash OR
    where previous_event_hash diverges from prior row's stored hash
  """
  def verify_audit_chain(actor_entity_id \\ nil) do
    rows =
      query_for_chain(actor_entity_id)
      |> Repo.all()

    do_verify(rows, nil, 0)
  end

  defp query_for_chain(nil) do
    from(a in AuditEvent,
      where: is_nil(a.actor_entity_id),
      order_by: [asc: a.timestamp]
    )
  end

  defp query_for_chain(actor_entity_id) when is_binary(actor_entity_id) do
    from(a in AuditEvent,
      where: a.actor_entity_id == ^actor_entity_id,
      order_by: [asc: a.timestamp]
    )
  end

  defp do_verify([], _prior_hash, count), do: {:ok, count}

  defp do_verify([row | rest], prior_hash, count) do
    # The previous_event_hash field must match the prior row's stored
    # event_hash (or be nil for the first row in the chain).
    if row.previous_event_hash != prior_hash do
      {:error,
       %{
         broken_at_audit_id: row.audit_id,
         expected_previous_hash: prior_hash,
         actual_previous_hash: row.previous_event_hash,
         reason: :previous_hash_mismatch
       }}
    else
      # Recompute event_hash from canonical_record; must match stored.
      computed =
        sha256_hex(
          canonical_record(%{
            audit_id: row.audit_id,
            event_type: row.event_type,
            actor_entity_id: row.actor_entity_id,
            target_entity_id: row.target_entity_id,
            target_capsule_id: row.target_capsule_id,
            session_id: row.session_id,
            outcome: row.outcome,
            denial_reason: row.denial_reason,
            details: row.details,
            ip_address: row.ip_address,
            timestamp: row.timestamp,
            previous_event_hash: row.previous_event_hash,
            lawful_basis_id: row.lawful_basis_id,
            lawful_basis_chain_hash: row.lawful_basis_chain_hash
          })
        )

      if computed != row.event_hash do
        {:error,
         %{
           broken_at_audit_id: row.audit_id,
           expected_hash: row.event_hash,
           computed_hash: computed,
           reason: :event_hash_mismatch
         }}
      else
        do_verify(rest, row.event_hash, count + 1)
      end
    end
  end
end
