defmodule CosmpRouter.Audit.CanonicalRecordTest do
  @moduledoc """
  Cross-language byte-equivalence tests for `CosmpRouter.Audit.canonical_record/1`
  + `sha256_hex/1` per ADR-0033 §Decision 4. Asserts that for every
  fixture generated by `scripts/generate-canonical-fixtures.ts` (the
  TypeScript register source-of-truth), the Elixir port produces an
  IDENTICAL canonical_input string AND an IDENTICAL SHA-256 hash.

  ## Why byte-equivalence matters

  `verify_audit_chain/1` running in EITHER language register must
  produce identical hashes for identical canonical inputs. If
  TypeScript writes a row + Elixir reads + recomputes the hash, the
  hashes must match — otherwise the chain integrity guarantee breaks
  at the language boundary.

  ## Fixture regeneration

  When this test fails, EITHER the Elixir port has drifted (fix the
  Elixir port to match TS) OR the TypeScript register's
  serialization discipline has changed (regenerate fixtures via
  `npx tsx scripts/generate-canonical-fixtures.ts` + verify Elixir
  port still matches the new fixtures).

  ## References

  - ADR-0033 §Decision 4a (canonical_record byte-equivalence) +
    §Decision 4b (canonical_json sorted-key discipline) + §Decision
    4d (sha256_hex)
  - `packages/database/src/queries/audit.ts` (TS source-of-truth)
  - `scripts/generate-canonical-fixtures.ts` (fixture generator)
  - `apps/cosmp_router/test/fixtures/canonical_record/fixtures.json`
    (test data)
  """

  use ExUnit.Case, async: true

  alias CosmpRouter.Audit

  @fixtures_path Path.expand(
                   "../../fixtures/canonical_record/fixtures.json",
                   __DIR__
                 )

  setup_all do
    fixtures =
      @fixtures_path
      |> File.read!()
      |> Jason.decode!()

    {:ok, fixtures: fixtures}
  end

  test "fixtures.json file exists at expected path" do
    assert File.exists?(@fixtures_path),
           "fixtures.json missing — run `npx tsx scripts/generate-canonical-fixtures.ts` to regenerate"
  end

  test "fixtures.json contains 8-16 representative cases per ADR-0033 spec + ADR-0042 §Q-ζ mutation-class extension",
       %{fixtures: fixtures} do
    # Phase 3 Sub-arc 2 Gap 1 G1.5 [CAPSULE-MUTATION-TESTS] per ADR-0042
    # §Sub-decision Q-ζ + Q-G1.5-ζ LOCK: upper bound widened from 12 to 16
    # to accommodate 4 NEW mutation-class fixtures (CAPSULE_MUTATION_ADD /
    # UPDATE / MERGE / NOOP) extending the 12-fixture ADR-0033 baseline.
    count = length(fixtures)
    assert count >= 8 and count <= 16, "fixture count #{count} out of expected band [8, 16]"
  end

  describe "canonical_record/1 byte-equivalence with TypeScript register" do
    test "every fixture produces identical canonical_input", %{fixtures: fixtures} do
      Enum.each(fixtures, fn fixture ->
        input = parse_fixture_input(fixture["input"])
        elixir_canonical = Audit.canonical_record(input)
        ts_canonical = fixture["canonical_input"]

        assert elixir_canonical == ts_canonical,
               """

               Byte-equivalence failure for fixture: #{fixture["description"]}

               TS canonical_input:
                 #{inspect(ts_canonical)}

               Elixir canonical_input:
                 #{inspect(elixir_canonical)}
               """
      end)
    end
  end

  describe "sha256_hex/1 byte-equivalence with TypeScript register" do
    test "every fixture's canonical_input hashes to the expected hex", %{fixtures: fixtures} do
      Enum.each(fixtures, fn fixture ->
        ts_canonical = fixture["canonical_input"]
        ts_expected_hash = fixture["expected_hash"]
        elixir_hash = Audit.sha256_hex(ts_canonical)

        assert elixir_hash == ts_expected_hash,
               """

               sha256_hex byte-equivalence failure for fixture: #{fixture["description"]}

               canonical_input: #{ts_canonical}
               TS expected_hash: #{ts_expected_hash}
               Elixir computed hash: #{elixir_hash}
               """
      end)
    end
  end

  describe "end-to-end: canonical_record/1 + sha256_hex/1 composition" do
    test "Elixir-built canonical_input + sha256_hex matches TS-computed expected_hash", %{
      fixtures: fixtures
    } do
      Enum.each(fixtures, fn fixture ->
        input = parse_fixture_input(fixture["input"])
        elixir_canonical = Audit.canonical_record(input)
        elixir_hash = Audit.sha256_hex(elixir_canonical)
        ts_expected_hash = fixture["expected_hash"]

        assert elixir_hash == ts_expected_hash,
               """

               End-to-end byte-equivalence failure for fixture: #{fixture["description"]}

               TS expected_hash: #{ts_expected_hash}
               Elixir hash:      #{elixir_hash}
               """
      end)
    end
  end

  # WHAT: Convert a fixture JSON object into a canonical_record/1
  #       parts map with proper Elixir types.
  # INPUT: Map decoded from fixtures.json with string keys.
  # OUTPUT: Map with atom keys + DateTime for :timestamp.
  # WHY: fixtures.json carries timestamp as ISO string for JSON
  #      portability; canonical_record/1 expects %DateTime{} so we
  #      parse here. Other optional fields stay as nil OR string
  #      depending on the fixture row.
  defp parse_fixture_input(raw) when is_map(raw) do
    {:ok, timestamp, _offset} = DateTime.from_iso8601(raw["timestamp"])

    %{
      audit_id: raw["audit_id"],
      event_type: raw["event_type"],
      actor_entity_id: raw["actor_entity_id"],
      target_entity_id: raw["target_entity_id"],
      target_capsule_id: raw["target_capsule_id"],
      session_id: raw["session_id"],
      outcome: raw["outcome"],
      denial_reason: raw["denial_reason"],
      details: raw["details"],
      ip_address: raw["ip_address"],
      timestamp: timestamp,
      previous_event_hash: raw["previous_event_hash"],
      # CAR Sub-box 3 sub-phase 4 [SUB-BOX-3-AUDIT-CHAIN-EXTENSION] per
      # ADR-0036 Sub-decision 5: positions 13 + 14 of canonical_record/1.
      lawful_basis_id: raw["lawful_basis_id"],
      lawful_basis_chain_hash: raw["lawful_basis_chain_hash"]
    }
  end
end
